### ISSUE TITLE
Update to R 3.5.2

### ISSUE THREAD

**Issue by stefanfritsch** [Microsoft/microsoft-r-open#90]
Hi,

in #86 you said the new version was going to be out sometime in February. Could we get another update on that? Are there particular holdups for 3.5.2?

In the RStudio 1.2 builds you now get errors for some of the GUI functionality ("run app" etc.) due to outdated packages. 

Thanks,
Stefan

**Comment by jeroenterheerdt** [comment]
we are still working on it, having some delays.

**Comment by jamesdalg** [comment]
Good to hear you're still working on it. I like the distribution, but it creates issues when others I work with use R 3.5.3 and use former versions of packages with slightly different syntax (e.g. tidyverse had some changes where drop=F became default for tibbles, which often causes incompatibilities when a function expects a vector rather than a data.frame). I've been using the checkpoint package, but it's not perfect, so this will be wonderful when it comes out.

**Comment by sentian** [comment]
Hi, 

Really enjoy using MRAN R. But given R 3.5.3 has been available for a while, can you please give an update on the upgrading process to 3.5.2?
